pknu-wap/Do-Learn

- backend/.gitignore
- backend/src/main/java/com/wap/web1/controller/StudyGroupController.java
- backend/src/main/java/com/wap/web1/domain/StudyGroup.java
- backend/src/main/java/com/wap/web1/dto/StudyGroupCreateDto.java
- backend/src/main/java/com/wap/web1/repository/StudyGroupRepository.java
- backend/src/main/java/com/wap/web1/repository/UserRepository.java
- backend/src/main/java/com/wap/web1/response/Response.java
- backend/src/main/java/com/wap/web1/security/CurrentUser.java
- backend/src/main/java/com/wap/web1/security/CustomUserDetails.java
- backend/src/main/java/com/wap/web1/security/CustomUserDetailsService.java
- backend/src/main/java/com/wap/web1/security/SecurityConfig.java
- backend/src/main/java/com/wap/web1/service/StudyGroupService.java
- backend/src/main/java/com/wap/web1/service/UserService.java
- 그룹명(중복안댐)
- 만남빈도수 (주 며칠)
- 시간(오전, 오후, 저녁)
- 모집 정원 (~10명)
- 공지사항
토큰 완료 후 leaderId관련 코드 수정, 다시 테스트 필요
> feat:스터디 생성코드

- backend/src/main/java/com/wap/web1/comfig/SecurityConfig.java
- backend/src/main/java/com/wap/web1/controller/MainController.java
- backend/src/main/java/com/wap/web1/controller/StudyGroupController.java
- backend/src/main/java/com/wap/web1/controller/UserController.java
- backend/src/main/java/com/wap/web1/domain/StudyGroup.java
- backend/src/main/java/com/wap/web1/dto/GroupPreviewDto.java
- backend/src/main/java/com/wap/web1/dto/MyGroupsDto.java
- backend/src/main/java/com/wap/web1/dto/MyInfoDto.java
- backend/src/main/java/com/wap/web1/dto/StudyGroupCreateDto.java
- backend/src/main/java/com/wap/web1/jwt/JWTFilter.java
- backend/src/main/java/com/wap/web1/jwt/LoginFilter.java
- backend/src/main/java/com/wap/web1/repository/StudyMemberRepository.java
- backend/src/main/java/com/wap/web1/service/StudyGroupService.java
- backend/src/main/java/com/wap/web1/service/UserService.java
- backend/src/main/resources/application.properties
> feature: 내 정보/가입한 그룹 조회

- backend/src/main/java/com/wap/web1/controller/StudyGroupController.java
- backend/src/main/java/com/wap/web1/domain/StudyGroup.java
- backend/src/main/java/com/wap/web1/dto/GroupMembersDto.java
- backend/src/main/java/com/wap/web1/dto/GroupNoticeDto.java
- backend/src/main/java/com/wap/web1/dto/GroupPreviewDto.java
- backend/src/main/java/com/wap/web1/dto/StudyGroupCreateDto.java
- backend/src/main/java/com/wap/web1/repository/StudyMemberRepository.java
- backend/src/main/java/com/wap/web1/service/StudyGroupService.java
- backend/src/main/resources/application.properties
공지, 멤버리스트 코드
+ 그룹명, 공지사항 글자수제한
> feature: 상세페이지1

- backend/.gitignore
- backend/src/main/java/com/wap/web1/jwt/JWTUtil.java
- backend/src/main/resources/application.properties
- backend/system.properties
> #33 deploy bugfix_1

- client/package-lock.json
- client/package.json
- client/src/assets/style/NavBar.scss
- client/src/assets/style/global.scss
- client/src/components/Layout.tsx
- client/src/components/NavBar.tsx
- client/src/pages/MainPage.tsx
> Feature : #32 nav bar 구현

- backend/src/main/java/com/wap/web1/comfig/SecurityConfig.java
- backend/src/main/java/com/wap/web1/controller/MainController.java
- backend/src/main/java/com/wap/web1/controller/SearchController.java
- backend/src/main/java/com/wap/web1/dto/StudyGroupResponse.java
- backend/src/main/java/com/wap/web1/repository/StudyGroupRepository.java
- backend/src/main/java/com/wap/web1/service/StudyGroupFilterSearchService.java
- backend/src/main/java/com/wap/web1/util/StudyGroupUtils.java
- backend/src/main/resources/application.properties
> Search and filter #30

- client/src/api/instance.ts
- client/src/api/studyGroupApi.ts
- client/src/features/studyGroupList/StudyGroupItem.tsx
- client/src/features/studyGroupList/StudyGroupsList.tsx
- client/src/hooks/useStudyGroups.ts
- client/src/pages/MainPage.tsx
> feature: 그룹 리스트 연동 및 수정

- backend/src/main/java/com/wap/web1/repository/UserRepository.java
- backend/src/main/java/com/wap/web1/service/JoinService.java
- backend/src/main/resources/application.properties
> 닉네임 중복 방지 (#65)

- client/src/features/login/SignupForm.scss
- client/src/features/login/SignupForm.tsx
- client/src/features/searchBar/SearchBar.tsx
- client/src/features/studyGroupForm/StudyGroupForm.scss
- client/src/features/studyGroupForm/StudyGroupForm.tsx
- client/src/features/studyGroupList/StudyGroupsList.scss
- client/src/features/studyGroupList/StudyGroupsList.tsx
- client/src/pages/MainPage.tsx
> DL FE #18 - 공지사항 최대 글자수 설정

- backend/src/main/java/com/wap/web1/comfig/SecurityConfig.java
- backend/src/main/java/com/wap/web1/controller/StudyGroupController.java
- backend/src/main/java/com/wap/web1/repository/StudyRankingRepository.java
- backend/src/main/java/com/wap/web1/service/StudyGroupService.java
- backend/src/main/resources/application.properties
상세페이지에 그룹명 전달코드,
멤버리스트 프로필을 랭킹별로 수정
> DL BE - 그룹명 전달

- client/src/features/login/SignupForm.tsx
> DL FE #88 - 닉네임 중복 검사 구현

- client/src/features/searchBar/SearchBar.tsx
#87 
서버가 이상한건지 뭐가 이상한건지 되는 듯 하면서도 되지 않음 .........
> DL FE #87 - 실시간 검색 결과 

- client/src/api/groupNotice.ts
- client/src/features/studyGroupList/GroupInfoModal.scss
- client/src/features/studyGroupList/GroupInfoModal.tsx
- client/src/features/studyGroupList/StudyGroupItem.tsx
스터디 그룹 가입 API 연동
공지사항 API 연동
모달창 UI 수정
> DL FE #90 - 스터디 그룹 가입 모달

- client/src/features/studyGroupForm/StudyGroupForm.tsx
> DL FE #101 - 그룹 생성 폼 403 오류 해결

- client/src/App.tsx
- client/src/api/auth.ts
- client/src/features/studyGroupList/GroupInfoModal.scss
- client/src/features/studyGroupList/GroupInfoModal.tsx
- client/src/features/studyGroupList/StudyGroupItem.tsx
- client/src/features/studyGroupList/StudyGroupsList.scss
- access 토큰 10분 후 만료 -> 9분마다 갱신
- 자동 로그인 여부에 따라 accessToken 저장 위치 분기 처리
> DL FE #107 - Access Token 리이슈 처리

- backend/src/main/java/com/wap/web1/dto/GroupMemberCount.java
- backend/src/main/java/com/wap/web1/repository/StudyMemberRepository.java
- backend/src/main/java/com/wap/web1/service/UserService.java
그룹 현재 인원수 세는 과정에서 너무 많은 반복이 되어 쿼리문으로 대체
> DL BE #9 - 내 그룹 리스트 현재 멤버 수 관련 수정

- backend/src/main/java/com/wap/web1/comfig/SecurityConfig.java
- backend/src/main/java/com/wap/web1/domain/User.java
- backend/src/main/java/com/wap/web1/dto/GroupMembersDto.java
- backend/src/main/java/com/wap/web1/dto/MyInfoDto.java
- backend/src/main/java/com/wap/web1/dto/MyInfoUpdateDto.java
- backend/src/main/java/com/wap/web1/scheduler/StudyScheduler.java
- backend/src/main/java/com/wap/web1/service/JoinService.java
- backend/src/main/java/com/wap/web1/service/StudyGroupService.java
- backend/src/main/java/com/wap/web1/service/UserService.java
1. 날짜를 한국기준 변경 #78
2. profileImage 값을 이미지링크에서 값으로 변경 #21
(1등 1, 2등 2, 3등 3, 4등부터 쭉 4)
3. 닉네임수정 유효성 검사(10자이내, 중복불가) 추가 #9
4. 스터디 생성, 수정 인원 (3~12) 수정 #7 #9
> DL BE - 유효성 검사 추가 등 코드수정

- client/src/api/myGroupsApi.ts
- client/src/api/myInfoApi.ts
- client/src/features/myGroupsList/MyGroupsList.tsx
- client/src/features/studyGroupList/GroupInfoModal.tsx
- client/src/features/studyGroupList/StudyGroupItem.tsx
- client/src/hooks/useMyStudyGroups.ts
- client/src/pages/MyPage.tsx
- 멤버 리스트에 사용자가 포함된 그룹 불러오기
- 방장인 그룹과 아닌 그룹 구분 필요 -> 백엔드에서 추가 후 수정
> DL FE #114 - 마이페이지 내 그룹 연동

- client/src/api/attendanceApi.ts
- client/src/features/groupDetail/tabs/AttendanceTab.scss
- client/src/features/groupDetail/tabs/AttendanceTab.tsx
> DL FE #128 - 오늘 날짜로 돌아가기 추가 구현

- backend/src/main/java/com/wap/web1/controller/UserController.java
- backend/src/main/java/com/wap/web1/repository/AttendanceRepository.java
- backend/src/main/java/com/wap/web1/repository/StudyMemberRepository.java
- backend/src/main/java/com/wap/web1/repository/StudyRankingRepository.java
- backend/src/main/java/com/wap/web1/service/StudyGroupService.java
- backend/src/main/java/com/wap/web1/service/UserService.java
> DL BE - 스터디 삭제 구현

- backend/src/main/java/com/wap/web1/controller/ProgressController.java
- backend/src/main/java/com/wap/web1/scheduler/ResetScheduler.java
- backend/src/main/java/com/wap/web1/service/MemberWeeklyPlanService.java
- backend/src/main/java/com/wap/web1/service/ProgressService.java
- backend/src/main/resources/application.properties
> DL BE - 진행도 구현

- backend/src/main/java/com/wap/web1/controller/RankingController.java
- backend/src/main/java/com/wap/web1/repository/StudyRankingRepository.java
- backend/src/main/java/com/wap/web1/repository/StudyRankingRepositoryCustom.java
- backend/src/main/java/com/wap/web1/repository/StudyRankingRepositoryImpl.java
- backend/src/main/java/com/wap/web1/scheduler/RankingScheduler.java
- backend/src/main/java/com/wap/web1/service/RankingService.java
> DL BE  - 랭킹 구현

- backend/.idea/compiler.xml
- backend/src/main/java/com/wap/web1/controller/MainController.java
- backend/src/main/java/com/wap/web1/dto/StudyGroupResponse.java
- backend/src/main/java/com/wap/web1/dto/StudyGroupWithMemberCountDto.java
- backend/src/main/java/com/wap/web1/mapper/StudyGroupMapper.java
- backend/src/main/java/com/wap/web1/repository/StudyGroupRepository.java
- backend/src/main/java/com/wap/web1/repository/StudyGroupRepositoryCustom.java
- backend/src/main/java/com/wap/web1/repository/StudyGroupRepositoryImpl.java
- backend/src/main/java/com/wap/web1/repository/StudyMemberRepository.java
- backend/src/main/java/com/wap/web1/service/StudyGroupListService.java
- backend/src/main/java/com/wap/web1/util/ScrollPaginationCollection.java
- backend/src/main/resources/application.properties
> DL BE #30 - 그룹리스트 및 필터링,검색기능

- backend/src/main/java/com/wap/web1/controller/MainController.java
- backend/src/main/java/com/wap/web1/domain/StudyRanking.java
- backend/src/main/java/com/wap/web1/dto/StudyRankDto.java
- backend/src/main/java/com/wap/web1/jwt/JWTFilter.java
- backend/src/main/java/com/wap/web1/jwt/LoginFilter.java
- backend/src/main/java/com/wap/web1/mapper/StudyGroupMapper.java
- backend/src/main/java/com/wap/web1/repository/StudyGroupRepositoryCustom.java
- backend/src/main/java/com/wap/web1/repository/StudyGroupRepositoryImpl.java
- backend/src/main/java/com/wap/web1/repository/StudyRankingRepository.java
- backend/src/main/java/com/wap/web1/service/RankingService.java
- backend/src/main/java/com/wap/web1/service/ReissueService.java
- backend/src/main/java/com/wap/web1/service/StudyGroupListService.java
> DL BE #143 - rankLevel 방식 수정

- client/src/features/groupDetail/tabs/RankingTab.tsx
> DL FE #162 - 1~3등 사이에 있는 유저가 아래 리스트에도 뜨는 오류 수정
